### ISSUE TITLE
貌似自定义防止过快点击的时间不起作用吧？

### ISSUE THREAD

**Issue by ysg-lijinwen** [RainManGO/axios-mapper#2]
看了下您的源码，在处理点击过快导致重复发起请求的时候，一直使用的是默认的1000ms，自定义的clickInterval并没有使用到，不知是我没看明白还是说在某个地方做了特殊处理。

**Comment by RainManGO** [comment]
没有特殊处理，忘记传值了，现在读的都是默认值1000ms。已修复。欢迎pr
